/* ——————————————— RULES ——————————————— */

const RULES = `
You are DfamoAI — a professional academic writing and formatting assistant that creates high-quality, well-structured assignments ready for direct PDF export.

When the user provides a topic or instructions:
1. Generate a full academic-style assignment with the following sections:
   - Title Page
   - Introduction
   - Main Sections (with headings and subheadings)
   - Conclusion
   - References (at least 3 credible academic sources)
2. Write in clear, formal, academic English with perfect grammar and logical flow.
3. Include explanations, examples, and detailed paragraphs under each section.
4. Format the response in Markdown ONLY.
5. # = main title (20pt bold), ## = section headings (16pt bold), ### = subheadings (14pt bold)
6. No meta text such as “Here is your assignment”
7. Must begin directly with the assignment title.
8. Must end exactly with:

---
*Generated by **DfamoAI** – Your Academic Writing Partner*
`;

/* ——————————————— API CALL ——————————————— */

async function generateAssignment(prompt) {
    const final = `${RULES}\nUser Request: ${prompt}`;

    const url = "https://text.pollinations.ai/" + encodeURIComponent(final);

    const response = await fetch(url);
    let text = await response.text();

    if (text.startsWith("<")) text = text.replace(/<[^>]*>/g, "");
    text = text.trim();

    if (!text || text.length < 20) throw new Error("Received invalid output.");

    return text;
}

/* ——————————————— PREVIEW RENDER ——————————————— */

function renderContent(content) {
    const lines = content.split("\n");
    let html = "";

    for (let line of lines) {
        if (line.startsWith("# ")) html += `<h1>${line.slice(2)}</h1>`;
        else if (line.startsWith("## ")) html += `<h2>${line.slice(3)}</h2>`;
        else if (line.startsWith("### ")) html += `<h3>${line.slice(4)}</h3>`;
        else html += `<p>${line}</p>`;
    }

    html += `<p class="signature">Generated by <strong>DfamoAI</strong> – Your Academic Writing Partner</p>`;
    return html;
}

/* ——————————————— PDF GENERATION ——————————————— */

function generatePDF(markdown) {
    const { jsPDF } = window.jspdf;
    const pdf = new jsPDF();

    const pageWidth = pdf.internal.pageSize.width - 20;
    const lineHeight = 8;
    let y = 20;

    const lines = markdown.split("\n");

    lines.forEach(line => {
        if (y > 280) {  
            pdf.addPage();
            y = 20;
        }

        if (line.startsWith("# ")) {
            pdf.setFontSize(20);
            pdf.setFont("Helvetica", "bold");
            pdf.text(line.replace("# ", ""), 10, y);
            y += 14;

        } else if (line.startsWith("## ")) {
            pdf.setFontSize(16);
            pdf.setFont("Helvetica", "bold");
            pdf.text(line.replace("## ", ""), 10, y);
            y += 12;

        } else if (line.startsWith("### ")) {
            pdf.setFontSize(14);
            pdf.setFont("Helvetica", "bold");
            pdf.text(line.replace("### ", ""), 10, y);
            y += 10;

        } else {
            pdf.setFontSize(12);
            pdf.setFont("Helvetica", "normal");

            const wrapped = pdf.splitTextToSize(line, pageWidth);
            wrapped.forEach(w => {
                if (y > 280) {
                    pdf.addPage();
                    y = 20;
                }
                pdf.text(w, 10, y);
                y += lineHeight;
            });
        }
    });

    pdf.save("DfamoAI-document.pdf");
}

/* ——————————————— DOM HANDLERS ——————————————— */

const form = document.getElementById("assignment-form");
const preview = document.getElementById("preview-content");
const previewEmpty = document.getElementById("preview-empty");
const buttons = document.getElementById("action-buttons");
const btnText = document.getElementById("btn-text");
const generateBtn = document.getElementById("generate-btn");

let generatedMarkdown = "";

form.addEventListener("submit", async e => {
    e.preventDefault();

    const prompt = document.getElementById("prompt").value.trim();
    if (!prompt) return;

    btnText.textContent = "Generating...";
    generateBtn.disabled = true;

    try {
        const output = await generateAssignment(prompt);
        generatedMarkdown = output;

        preview.innerHTML = renderContent(output);

        preview.classList.remove("hidden");
        previewEmpty.classList.add("hidden");
        buttons.classList.remove("hidden");

    } catch (err) {
        alert("Error: " + err.message);
    }

    btnText.textContent = "Generate Document";
    generateBtn.disabled = false;
});

/* ——— DOWNLOAD PDF ——— */
document.getElementById("download-btn").addEventListener("click", () => {
    if (!generatedMarkdown) {
        alert("No document to download.");
        return;
    }
    generatePDF(generatedMarkdown);
});

/* ——— CLEAR ——— */
document.getElementById("clear-btn").addEventListener("click", () => {
    generatedMarkdown = "";
    preview.innerHTML = "";
    preview.classList.add("hidden");
    previewEmpty.classList.remove("hidden");
    buttons.classList.add("hidden");
});
